server:
    port: 8080
    servlet:
      context-path: /sharehoo
shop:
   solr-host: http://106.13.75.153:8010/solr/collection1
   
forum:
   leavemessage:
        SECRET_TOPIC: 40
   topic:
        #index.jsp--topics--count 2018.08.10
        NEW_TOPIC: 13
        YUAN_TOPIC: 15
        CHU_TOPIC: 15
        RECOMMEND: 15
        
        #topic--secret--count 2018.11.29
        SECRET_TOPIC: 40
        #solr_search.jsp--source--count 2018.08.17
        SEARCH_RESULT_ROWS: 10
        SEARCH_TOPIC_RESULT_ROWS: 15
        
        #redis
        YUAN_CHUANG: YUAN_CHUANG
        ADVICE: ADVICE
        JAVAWEB: JAVAWEB
        ERSHOU: ERSHOU
        MONEY: MONEY
        JOB_INTERVIEW: JOB_INTERVIEW
        CODE: CODE
        SAY: SAY
        WEB: WEB
        GAME: GAME
        SERVERDEV: SERVERDEV
        MUSIC: MUSIC
        FRIEND: FRIEND
        BIGDATA: BIGDATA
        WECHAT: WECHAT
        FOOD: FOOD
        GAMEDEV: GAMEDEV
        
   #sharehoo---water marker 2018.08.21
   WATER_MARK_PATH: C:/apache-tomcat-7.0.55/webapps/Forum/images/topicImage/
   WATER_NARK_CONTENT: sharehoo社区
   
spring:
    profiles:
      active: dev
    
    #2019.09.10 miki 设置topic的freemarker模板引擎文件的路径
    freemarker:
        HTML_GEN_PATH: D:/soft/freemarker/
        template-loader-path: classpath:/templates/
        #- /templates/
        #- file:./templates/
        cache: false
        settings:
            classic_compatible: true #处理空值
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/db_forum?useSSL=false&characterEncoding=utf8
        username: root
        password: root
        #type: mysql
        # 采购信息库
        dbtype: mysql
        dbuser: root
        dbpwd: root
        dbip:  127.0.0.1  # 10.192.0.190     #127.0.0.1--2019.12.30 miki 改用百度云服务器作为数据库服务器，减少网站服务器的压力
        dbport: 3306
        dbname: db_forum
        #pid: 5899
        path: project/reports/wechat
        fid:
        
    #springboot 集成hibernate 2019.07.04  miki
    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: none   #暂时用不到
            naming: 
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   #2019.08.14 驼峰命名字段时，不让jpa大写转小写字段      
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ./indexes
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        open-in-view: true
    #2019.09.13 miki 社区首页数据缓存
    redis: 
        host: 106.13.75.153
        password:
        port: 6379   
        timeout: 0
        jedis:
          pool:
            max-active: 8
            max-idle: 8  
            min-idle: 0
            max-wait: -1
    data:
        solr:
          host: http://106.13.75.153:8010/solr-topic/collection1   
              
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 0
            max-file-size: 100MB     #2019.09.08 miki 配置店铺上传资源的最大值
            max-request-size: 100MB   #2019.09.08 miki 配置文件最大下载大小 
    
            
    # 2019.07.04  miki  配置springboot访问jsp页面
    mvc:
        view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
    
    site:
        store:
            root: /data/sharehoo
            # 存储模式, 可选值 absolute / relative
            repo: relative

            # 是否开启资源域名
            domain: false

            # ---------------------------------
            # 资源域名, resource.domain = true 是有效
            # 配置域名, 将域名的根目录指向 store.root 配置的地址
            # ---------------------------------
            host: http://sharehoo.cn

logging:
  file: /../../idp/logs/dip/dip.log #${catalina.home}/../../idp/logs/dip/dip.log